# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\telaTransfere.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Tela_Transferir(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(356, 335)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 40, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.botao_transferir = QtWidgets.QPushButton(self.centralwidget)
        self.botao_transferir.setGeometry(QtCore.QRect(140, 210, 75, 23))
        self.botao_transferir.setObjectName("botao_transferir")
        self.botao_voltar = QtWidgets.QPushButton(self.centralwidget)
        self.botao_voltar.setGeometry(QtCore.QRect(280, 270, 75, 23))
        self.botao_voltar.setObjectName("botao_voltar")
        self.input_valor = QtWidgets.QLineEdit(self.centralwidget)
        self.input_valor.setGeometry(QtCore.QRect(80, 170, 201, 20))
        self.input_valor.setObjectName("input_valor")
        self.input_conta = QtWidgets.QLineEdit(self.centralwidget)
        self.input_conta.setGeometry(QtCore.QRect(80, 140, 201, 20))
        self.input_conta.setObjectName("input_conta")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Transferencia"))
        self.botao_transferir.setText(_translate("MainWindow", "Tranferir"))
        self.botao_voltar.setText(_translate("MainWindow", "Voltar"))
        self.input_valor.setPlaceholderText(_translate("MainWindow", "Valor da Transferencia"))
        self.input_conta.setPlaceholderText(_translate("MainWindow", "Id_conta"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Tela_Transferir()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
