# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'telaCadastra.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Tela_Cadastra(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(387, 284)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 10, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.input_nome = QtWidgets.QLineEdit(self.centralwidget)
        self.input_nome.setGeometry(QtCore.QRect(90, 70, 201, 20))
        self.input_nome.setObjectName("input_nome")
        self.input_sobrenome = QtWidgets.QLineEdit(self.centralwidget)
        self.input_sobrenome.setGeometry(QtCore.QRect(90, 90, 201, 20))
        self.input_sobrenome.setObjectName("input_sobrenome")
        self.input_cpf = QtWidgets.QLineEdit(self.centralwidget)
        self.input_cpf.setGeometry(QtCore.QRect(90, 110, 201, 20))
        self.input_cpf.setObjectName("input_cpf")
        self.botao_cadastra = QtWidgets.QPushButton(self.centralwidget)
        self.botao_cadastra.setGeometry(QtCore.QRect(150, 150, 75, 23))
        self.botao_cadastra.setObjectName("botao_cadastra")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(310, 240, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Informacoes - Pessoais"))
        self.input_nome.setPlaceholderText(_translate("MainWindow", "Nome"))
        self.input_sobrenome.setPlaceholderText(_translate("MainWindow", "Sobrenome"))
        self.input_cpf.setPlaceholderText(_translate("MainWindow", "CPF"))
        self.botao_cadastra.setText(_translate("MainWindow", "Cadastra"))
        self.pushButton_2.setText(_translate("MainWindow", "Voltar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Tela_Cadastra()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
