# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\telaSacar.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Tela_Sacar(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(404, 298)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(190, 20, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.botao_voltar = QtWidgets.QPushButton(self.centralwidget)
        self.botao_voltar.setGeometry(QtCore.QRect(320, 250, 75, 23))
        self.botao_voltar.setObjectName("botao_voltar")
        self.input_sacar = QtWidgets.QLineEdit(self.centralwidget)
        self.input_sacar.setGeometry(QtCore.QRect(90, 120, 201, 20))
        self.input_sacar.setObjectName("input_sacar")
        self.botao_sacar = QtWidgets.QPushButton(self.centralwidget)
        self.botao_sacar.setGeometry(QtCore.QRect(300, 120, 75, 23))
        self.botao_sacar.setObjectName("botao_sacar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Sacar"))
        self.botao_voltar.setText(_translate("MainWindow", "Voltar"))
        self.input_sacar.setPlaceholderText(_translate("MainWindow", "valor do saque"))
        self.botao_sacar.setText(_translate("MainWindow", "Sacar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Tela_Sacar()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
