# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\telaInicial.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Tela_Inicia(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(238, 270)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 30, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.botao_cadpessoa = QtWidgets.QPushButton(self.centralwidget)
        self.botao_cadpessoa.setGeometry(QtCore.QRect(70, 110, 101, 23))
        self.botao_cadpessoa.setObjectName("botao_cadpessoa")
        self.botao_singin = QtWidgets.QPushButton(self.centralwidget)
        self.botao_singin.setGeometry(QtCore.QRect(70, 170, 101, 23))
        self.botao_singin.setObjectName("botao_singin")
        self.botao_cadconta = QtWidgets.QPushButton(self.centralwidget)
        self.botao_cadconta.setGeometry(QtCore.QRect(70, 140, 101, 23))
        self.botao_cadconta.setObjectName("botao_cadconta")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Menu - Conta"))
        self.botao_cadpessoa.setText(_translate("MainWindow", "Cadastrar Pessoa"))
        self.botao_singin.setText(_translate("MainWindow", "Sing-in"))
        self.botao_cadconta.setText(_translate("MainWindow", "Cadastrar Conta"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Tela_Inicia()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
